### PR TITLE
Export plone.app.redirector redirects, if available

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@thet this is ready; can we have a new release after merging it?

**Comment by hvelarde** [comment]
@erral I think this should be a little bit different; I was about to add a redirects section to plone.app.transmogrifier and the I discovered there's already one there and it works a little bit different:

https://github.com/collective/plone.app.transmogrifier/blob/master/src/plone/app/transmogrifier/redirector.py

the section is quite complex and seems to do many things that I don't understand but there are 2 important things that I need to change: key name (must be `_old_paths`, which is kind of ugly) and I have to remove the site name from the values (currently in my tests it's adding `/Plone`).

you can check the documentation here:

https://github.com/collective/plone.app.transmogrifier/blob/master/src/plone/app/transmogrifier/redirector.rst

**Comment by hvelarde** [comment]
now the output is something like:

```json
    "_old_paths": [
        "/baz",
        "/foo"
    ],
```

**Comment by erral** [comment]
Now that I check some of my pipelines, I see that I used it indeed...

It looks like this blueprint not only handles plone.app.redirector redirects, but also changes the value for some other attributes.

In any case I'm OK with your changes.

**Comment by hvelarde** [comment]
@thet if you're too busy please add the `collective` user as a package owner/maintainer into PyPI.

**Comment by thet** [comment]
Who has access to the collective user on pypi? There was recently a discussion anywhere stating that Alan Runyan has access.

However, it's in Plone hands and in general a good idea to spread pypi ownership. Done.

**Comment by hvelarde** [comment]
@thet seems nobody has the collective user password, do you mind to add me to the list or package maintainers?

**Comment by djay** [comment]
Wasn't it originally written by @garbas ?

**Comment by hvelarde** [comment]
@djay we already solved the issue.

**Pull request merged**
